[custom.all.compiler-tools]
type = "local"
path = "."
ipkg = "compiler-tools.ipkg"
test = "test/compiler-tools-test.ipkg"

[custom.all.compiler-tools-test]
type = "local"
path = "test"
ipkg = "compiler-tools-test.ipkg"

[custom.all.dependent-map]
type   = "github"
url    = "git@github.com:JankaGramofonomanka/idris-dependent-map"
commit = "45b7da745313a4ba15ecf48c572f7b2559e204f2"
ipkg   = "dependent-map.ipkg"

[custom.all.doc]
type   = "github"
url    = "git@github.com:JankaGramofonomanka/idris-doc"
commit = "49f261841292a421af029b61ff6804b1b4f30ee0"
ipkg   = "doc.ipkg"

[custom.all.misc]
type   = "github"
url    = "git@github.com:JankaGramofonomanka/idris-misc.git"
commit = "90e4a3c3c0b376c29ba89522b0568a66f1857800"
ipkg   = "misc.ipkg"

[custom.all.dtypes]
type   = "github"
url    = "git@github.com:JankaGramofonomanka/idris-dtypes.git"
commit = "11dd08baacdf98df28aa6d034bf6ff30976f298d"
ipkg   = "dtypes.ipkg"
