[custom.all.compiler-tools]
type = "local"
path = "."
ipkg = "compiler-tools.ipkg"
test = "test/compiler-tools-test.ipkg"

[custom.all.compiler-tools-test]
type = "local"
path = "test"
ipkg = "compiler-tools-test.ipkg"

[custom.all.dependent-map]
type   = "github"
url    = "git@github.com:JankaGramofonomanka/idris-dependent-map"
commit = "a2c396e9e4b19643517becc4fabedea9b144c6cf"
ipkg   = "dependent-map.ipkg"

[custom.all.doc]
type   = "github"
url    = "git@github.com:JankaGramofonomanka/idris-doc"
commit = "49f261841292a421af029b61ff6804b1b4f30ee0"
ipkg   = "doc.ipkg"

[custom.all.misc]
type   = "github"
url    = "git@github.com:JankaGramofonomanka/idris-misc.git"
commit = "9095834baf8ac96e58ef81b21e96ae734e9d1896"
ipkg   = "misc.ipkg"
