[custom.all.lng-compiler]
type = "local"
path = "lng-compiler"
ipkg = "lng-compiler.ipkg"
test = "test/lng-compiler-test.ipkg"

[custom.all.lng-compiler-test]
type = "local"
path = "lng-compiler/test"
ipkg = "lng-compiler-test.ipkg"

[custom.all.control-flow]
type = "local"
path = "control-flow"
ipkg = "control-flow.ipkg"
test = "test/test.ipkg"

[custom.all.control-flow-test]
type = "local"
path = "control-flow/test"
ipkg = "test.ipkg"

[custom.all.doc]
type   = "github"
url    = "https://github.com/JankaGramofonomanka/idris-doc.git"
commit = "49f261841292a421af029b61ff6804b1b4f30ee0"
ipkg   = "doc.ipkg"

[custom.all.misc]
type   = "github"
url    = "https://github.com/JankaGramofonomanka/idris-misc.git"
commit = "24669b06020f032f5e49a311f1247ecd401a3de5"
ipkg   = "misc.ipkg"

[custom.all.theory]
type   = "github"
url    = "https://github.com/JankaGramofonomanka/idris-theory.git"
commit = "752f60e7e925761dfdb1d3cc05cdff7b2d69082f"
ipkg   = "theory.ipkg"
