[custom.all.lng-compiler]
type = "local"
path = "lng-compiler"
ipkg = "lng-compiler.ipkg"
test = "test/lng-compiler-test.ipkg"

[custom.all.lng-compiler-test]
type = "local"
path = "lng-compiler/test"
ipkg = "lng-compiler-test.ipkg"

[custom.all.dependent-map]
type   = "github"
url    = "https://github.com/JankaGramofonomanka/idris-dependent-map.git"
commit = "78be44d596bd4a47f686f6b0137f244553d22b59"
ipkg   = "dependent-map.ipkg"

[custom.all.doc]
type   = "github"
url    = "https://github.com/JankaGramofonomanka/idris-doc.git"
commit = "49f261841292a421af029b61ff6804b1b4f30ee0"
ipkg   = "doc.ipkg"

[custom.all.misc]
type   = "github"
url    = "https://github.com/JankaGramofonomanka/idris-misc.git"
commit = "24669b06020f032f5e49a311f1247ecd401a3de5"
ipkg   = "misc.ipkg"

[custom.all.dtypes]
type   = "github"
url    = "https://github.com/JankaGramofonomanka/idris-dtypes.git"
commit = "028eb21c8f157037b2fa75e3f911cb33471e2774"
ipkg   = "dtypes.ipkg"

[custom.all.theory]
type   = "github"
url    = "https://github.com/JankaGramofonomanka/idris-theory.git"
commit = "752f60e7e925761dfdb1d3cc05cdff7b2d69082f"
ipkg   = "theory.ipkg"
