name: CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack:latest

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install --yes llvm
    - uses: actions/checkout@v4

    - name: Build project
      run: pack build lng-compiler

    - name: "Unit tests: Build test suite"
      run: pack build lng-compiler-test
    - name: "Unit tests: Run tests"
      run: pack test lng-compiler

    - name: "E2E: Compile example code"
      run: ./scripts/compile
    - name: "E2E: Run the compiled examples"
      run: ./scripts/test
    - name: "E2E: Cleanup after tests"
      run: ./scripts/clean
